# Generated by Django 5.0.5 on 2024-05-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
