# Generated by Django 5.0.5 on 2024-05-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_subscriber_end_date_subscriber_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
