# Generated by Django 5.0.5 on 2024-06-07 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_tenant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('Z', 'Z')], max_length=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan_subscription',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Temporary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_api.subscription')),
                ('temp_subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_api.subscriber')),
                ('temp_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_api.tenant')),
            ],
        ),
    ]
